var KEYS=require('../../../utils/stat-calc').BUILD_SLOT_KEYS,getClassMeta=require('../../../utils/class-data').getClassMeta;
var flatten=require('../../../utils/equipment').flattenItems,crafting=require('../../../utils/crafting'),weapon=require('../../../utils/weapon-rules'),builds=require('../../../utils/builds');
var TYPES=['crit','haste','mastery','versatility'],LIMIT=900,MAX=100000;
function pos(n){return typeof n==='number'&&isFinite(n)&&Math.floor(n)===n&&n>0&&n<=9007199254740991;}
function stat(n){return pos(n)&&n<=MAX;}
function encoded(s){try{return encodeURIComponent(s).length;}catch(e){return Infinity;}}
function valid(c,s){return typeof c==='string'&&!!getClassMeta(c)&&pos(s)&&s<=9999;}
function number(s){var n=typeof s==='string'&&/^[1-9][0-9]*$/.test(s)?Number(s):null;return pos(n)?n:null;}
function parseCraft(part,slots,overrides){var p=part.split(':'),key=p[1],used={},list=[];if(p.length<4||p.length%2||p[0]!=='craft'||KEYS.indexOf(key)<0||!slots[key]||overrides[key])return false;for(var i=2;i<p.length;i+=2){var type=p[i],value=number(p[i+1]);if(TYPES.indexOf(type)<0||used[type]||!stat(value))return false;used[type]=true;list.push({type:type,value:value});}if(!list.length||list.length>2)return false;overrides[key]=list;return true;}
function parseBuildSharePayload(payload){if(typeof payload!=='string'||!payload||encoded(payload)>LIMIT)return null;var p=payload.split('|'),classKey=p[1],specId=number(p[2]);if(p.length<3||p[0]!=='v2'||!valid(classKey,specId))return null;var slots={},craftingOverrides={},count=0;for(var i=3;i<p.length;i++){var part=p[i];if(!part)return null;if(part.indexOf('craft:')===0){if(!parseCraft(part,slots,craftingOverrides))return null;count+=craftingOverrides[part.split(':')[1]].length;if(count>16)return null;continue;}var f=part.split(':');if(f.length!==2||KEYS.indexOf(f[0])<0||slots[f[0]])return null;var id=number(f[1]);if(!id)return null;slots[f[0]]=id;}return {version:2,classKey:classKey,specId:specId,slots:slots,craftingOverrides:craftingOverrides};}
function supports(item,spec){return !Array.isArray(item.specs)||!item.specs.length||item.specs.indexOf(Number(spec))>=0;}
function fits(item,key,spec){if(!item||!supports(item,spec))return false;if(key==='weapon'||key==='weapon2')return weapon.canItemUseSlot(spec,key,item);if(key==='finger1'||key==='finger2')return item.slot==='finger';if(key==='trinket1'||key==='trinket2')return item.slot==='trinket';return item.slot===key;}
function resolveCraft(item,selected){if(!selected)return item;var slots=crafting.getRandomAttributeSlots(item);if(!slots.length||slots.length!==selected.length)return null;for(var i=0;i<slots.length;i++)if(Number(slots[i].value)!==Number(selected[i].value))return null;return crafting.buildCraftedItemWithSelectedStats(item,selected.map(function(x){return x.type;}));}
function validateAndBuildSharedSlots(parsed,classData){var spec=parsed&&classData&&classData.class&&classData.class.key===parsed.classKey&&Array.isArray(classData.specs)&&classData.specs.find(function(x){return Number(x.id)===Number(parsed.specId);});if(!spec)return null;var map={},slots=builds.emptySlots(),unique={};flatten(classData.instances||[]).forEach(function(item){if(item&&Number(item.id)>0&&!map[item.id])map[item.id]=item;});var keys=Object.keys(parsed.slots||{});for(var i=0;i<keys.length;i++){var key=keys[i],item=map[parsed.slots[key]];if(KEYS.indexOf(key)<0||slots[key]||!fits(item,key,parsed.specId)||(item.tooltipFlags&&item.tooltipFlags.uniqueEquipped&&unique[item.id]))return null;item=resolveCraft(item,parsed.craftingOverrides&&parsed.craftingOverrides[key]);if(!item)return null;slots[key]=builds.buildItemSnapshot(item);if(item.tooltipFlags&&item.tooltipFlags.uniqueEquipped)unique[item.itemId]=true;}var clean=weapon.sanitizeWeaponSlots(slots,parsed.specId);return clean.changed?null:{slots:clean.slots,spec:spec};}
function persistSharedBuild(parsed,classData){var result=validateAndBuildSharedSlots(parsed,classData);if(!result)return null;var now=Date.now(),all=builds.getBuilds(),build={id:'build_'+now,name:classData.class.name+' · '+result.spec.name,classKey:parsed.classKey,className:classData.class.name,specId:parsed.specId,specName:result.spec.name,slots:result.slots,draft:true,createdAt:now,updatedAt:now};build.summary=builds.summarizeBuild(build);all.unshift(build);builds.saveBuilds(all);return build;}
function restoreWclPreset(options){var classKey=options.classKey,specId=Number(options.specId),fileKey=options.wclFileKey,presetId=options.wclPresetId,contentType=options.wclContent;if(!getClassMeta(classKey)||!specId||!fileKey||!presetId||['mythicPlus','raid'].indexOf(contentType)<0)return Promise.resolve(null);var data=require('../../../utils/class-data'),wcl=require('../../../utils/wcl-presets');return Promise.all([data.loadClassData(classKey),wcl.loadWclPresetIndex(classKey,specId)]).then(function(values){var classData=values[0],index=values[1],spec=classData&&(classData.specs||[]).find(function(x){return Number(x.id)===specId;}),categories=contentType==='raid'&&index?index.raid:(index&&index.mythicPlus);if(!spec||!index||index.classKey!==classKey||Number(index.specId)!==specId||!(categories||[]).some(function(x){return x.fileKey===fileKey;}))return null;return wcl.loadWclPresetFile(classKey,specId,fileKey).then(function(content){if(!content||content.classKey!==classKey||Number(content.specId)!==specId||(contentType==='raid'?'raid':'mythic-plus')!==content.contentType)return null;var preset=null;(content.entries||[]).some(function(entry){preset=(entry.presets||[]).find(function(x){return x.id===presetId;})||null;return !!preset;});if(!preset)return null;var build=builds.createBuild(classKey,classData.class.name,specId,spec.name,true),result=wcl.applyWclPresetToBuild(build.id,preset,classData,specId,builds.emptySlots(),{enabled:wcl.hasWclCombatantSnapshot(index,content),fileKey:fileKey,contentType:contentType});if(!result||!result.build){builds.deleteBuild(build.id);return null;}return result.build;});});}
module.exports={parseBuildSharePayload:parseBuildSharePayload,validateAndBuildSharedSlots:validateAndBuildSharedSlots,persistSharedBuild:persistSharedBuild,restoreWclPreset:restoreWclPreset};
